<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Y42S3X\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Y42S3X/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container1Y42S3X.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container1Y42S3X\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container1Y42S3X\App_KernelProdContainer([
    'container.build_hash' => '1Y42S3X',
    'container.build_id' => '716abc5f',
    'container.build_time' => 1617354933,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Y42S3X');
