<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_fact' => [[], ['_controller' => 'App\\Controller\\AddFactController::index'], [], [['text', '/add/fact']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/floadmin']], [], []],
    'factjson' => [[], ['_controller' => 'App\\Controller\\AjaxController::index'], [], [['text', '/factjson']], [], []],
    'factjson_all' => [[], ['_controller' => 'App\\Controller\\AjaxController::jsonActionAll'], [], [['text', '/factjson/all']], [], []],
    'factjson_random' => [[], ['_controller' => 'App\\Controller\\AjaxController::jsonActionOne'], [], [['text', '/factjson/random']], [], []],
    'factjson_auteur' => [['auteur'], ['_controller' => 'App\\Controller\\AjaxController::jsonActionAuteur'], [], [['variable', '/', '[^/]++', 'auteur', true], ['text', '/factjson/auteurs']], [], []],
    'factjson_list' => [[], ['_controller' => 'App\\Controller\\AjaxController::jsonActionList'], [], [['text', '/factjson/list']], [], []],
    'fact_random' => [[], ['_controller' => 'App\\Controller\\FactRandomController::index'], [], [['text', '/fact/random']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
