<?php

namespace Container1Y42S3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddFactTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AddFactType' shared autowired service.
     *
     * @return \App\Form\AddFactType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddFactType.php';

        return $container->privates['App\\Form\\AddFactType'] = new \App\Form\AddFactType();
    }
}
