<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxT0VXl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxT0VXl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxT0VXl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxT0VXl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxT0VXl\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxT0VXl',
    'container.build_id' => '870ce519',
    'container.build_time' => 1617279597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxT0VXl');
